name: mint
description: Mint.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  pedantic: ^1.11.1

flutter:
  uses-material-design: true

import_sorter:
  comments: false