name: mint
description: Mint.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.4
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  fluentui_system_icons: ^1.1.142
  flutter:
    sdk: flutter
  flutter_tts: ^3.2.2
  get_it: ^7.2.0
  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  pedantic: ^1.11.1

flutter:
  assets:
    - assets/illustrations/
    - assets/sample_images/
  fonts:
    - family: Red Hat Text
      fonts:
        - asset: assets/fonts/red_hat/RedHatText-Regular.ttf
          weight: 400
        - asset: assets/fonts/red_hat/RedHatText-Medium.ttf
          weight: 500
        - asset: assets/fonts/red_hat/RedHatText-Bold.ttf
          weight: 700
    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/red_hat/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/red_hat/RedHatDisplay-Bold.ttf
          weight: 700
  uses-material-design: true

import_sorter:
  comments: false