@startuml
autonumber "<b>Step 0: "
hide footbox
skinparam maxMessageSize 200
skinparam titleFontSize 24
skinparam participantFontName Monospaced
skinparam participantFontStyle bold

title Sequence of internal calls between UI and Controller in Example MVC.\n

actor User
participant "RandomRecipeButton" as button
participant "RecipeLabel" as label
participant "RandomRecipeController" as controller

User -> button: Presses button\n<i>"I want a random recipe please"
button -> controller : ""requestRandomRecipe()""\nAsk controller to generate random recipe.

note over controller : In an actual app, there will be more logic\nhere, such as database read/write.

controller -> label : ""notifyListeners()""\nNotify all listeners something changed
note over label: Many widgets can be notified by\ncontroller. In this example, only\n""RecipeLabel"" needs to do something\nabout the change.

label -> controller : Calls ""randomRecipe"" getter\n(Consumer's builder handles this)
controller --> label : ""randomRecipe"" is returned
note right of label: ""randomRecipe"" is a model.

label -> label : Label rebuilds with new\nname from ""randomRecipe""
label --> User : User sees new random recipe :)
@enduml