@startuml

class Recipe {
    + id : String
    + name : String
    + imageUrl : String? [nullable]
    + steps : List<RecipeStep>? [nullable]
}

class RecipeStep {
    + instruction : String
    + imageUrl : String? [nullable]
}

Recipe *--- RecipeStep

@enduml